Feature/object capture
Banhana/DesignScape-AR pull request #23
Opened 2024-03-04 04:35 UTC by Banhana

Recreation of the scanned model still in progress.

2024-03-08 08:12 UTC, hthm00 commented
change color to theme color

2024-04-16 01:07 UTC, hthm00 requested changes
merge my pull request for changes

2024-04-23 22:40 UTC, hthm00 approved these changes

2024-04-25 21:52 UTC, Banhana commented
Ignore this PR. Ruined the merging.

2024-04-25 21:52 UTC, closed without merging