Untitled Pull Request
Banhana/DesignScape-AR pull request #25
Opened 2024-03-14 04:44 UTC by nhuy703

Added save to favorite function
Fixed sign in & sign up UI

2024-03-17 01:07 UTC, hthm00 requested changes
- Save designs always show 2 items
<img width="344" alt="Screenshot 2024-03-16 at 6 05 15 PM" src="https://github.com/Banhana/DesignScape-AR/assets/38261965/46554b32-fd59-41dd-91b5-a81523fb65ee">

- App crashes when trying to favorite an item without login
<img width="797" alt="Screenshot 2024-03-16 at 6 07 17 PM" src="https://github.com/Banhana/DesignScape-AR/assets/38261965/9a9f6adc-53bd-4ffc-b3e4-0a5006ed8de4">

2024-04-02 20:34 UTC, hthm00 requested changes

2024-04-02 20:34 UTC, hthm00 commented on DesignScape/DesignScape/View/Product/FavoritesView.swift
> +                    if let product = productViewModel.product {
this line cause repeated favorite items bug. see below
![Screenshot 2024-04-02 at 1 33 20 PM](https://github.com/Banhana/DesignScape-AR/assets/38261965/9fa5394a-db35-47c8-8b6f-7c2afe5f83e7)

2024-04-07 00:13 UTC, nhuy703 commented on DesignScape/DesignScape/View/Product/FavoritesView.swift
> +                    if let product = productViewModel.product {
I fixed it hehe

2024-04-07 00:30 UTC, hthm00 approved these changes
Excellent work. I am so proud of you!

2024-04-07 01:49 UTC, merged