Feature/object removal
Banhana/DesignScape-AR pull request #32
Opened 2024-04-09 22:10 UTC by Banhana

2024-04-10 20:48 UTC, hthm00 requested changes

2024-04-27 20:24 UTC, Banhana commented on DesignScape/DesignScape/View/CameraView.swift
> +                modelNames = loadModelNamesFromPlist(named: "Furniture") // Function is in ModelLoader.swift
No error, the icons just don't show up in the view, so I can't place anything.

2024-04-27 20:27 UTC, Banhana commented on DesignScape/DesignScape/View/CustomARView.swift
>      func placeObject(modelName: String) {
CustomARView isn't an actual UI View file. It holds all the functions for my CameraView. I should have named it better but it was the first file I made for this project back in February.

2024-04-28 20:52 UTC, Banhana commented
Broke branch after merging so made a new one with the new commits and fixes.

2024-04-28 20:52 UTC, closed without merging